rules:
  - metadata:
      kind: prequel
      id: AwCupRNgNxuCPkhacvRn73
    cre:
      id: CRE-2025-0079
      severity: 1
      title: "Redpanda Startup and Storage Failures"
      category: "Data Streaming Platforms"
      author: Prequel
      description: |
        Detects Redpanda startup failures and operational issues impacting cluster stability.

        Identifies configuration issues, system resource problems, performance monitoring 
        failures, and operational concerns that can lead to degraded performance, data 
        corruption, or service failure.
      tags:
        - redpanda
        - startup-failure
        - configuration-error
        - memory-allocation
        - filesystem-compatibility
        - crash-protection
        - broker-health
      applications:
        - name: "Redpanda Data Streaming Platform"
          version: "22.x, 23.x, 24.x+"
        - name: "Apache Kafka Compatible Systems"
          version: "2.8+, 3.x"
        - name: "Confluent Platform"
          version: "6.x, 7.x+"
      mitigation: |
        **Immediate Actions:**
        - Check Redpanda service status and restart if necessary
        - Verify configuration file permissions and existence
        - Review system resource allocation (memory, disk space)

        **Configuration Fixes:**
        - Ensure config files exist with proper permissions
        - Set appropriate file ownership (redpanda:redpanda)
        - Verify configuration syntax and parameters

        **System Optimization:**
        - Increase memory allocation to minimum 1GB+
        - Use XFS or ext4 filesystem for optimal performance
        - Set /proc/sys/kernel/perf_event_paranoid to 1 or lower
      references:
        - "Redpanda Documentation: https://docs.redpanda.com/"
        - "Configuration Reference: https://docs.redpanda.com/current/reference/properties/"
        - "System Requirements: https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/manual/production/requirements/"
    rule:
      set:
        event:
          source: cre.log.redpanda
        window: 300s
        match:
          # Configuration file loading failures
          - regex: "Can't load config cache"
          - regex: "Can't load config bootstrap file"
          - regex: "No such file or directory.*config_cache\\.yaml"
          - regex: "No such file or directory.*\\.bootstrap\\.yaml"

          # System checks and warnings
          - regex: "syschecks - Memory.*below recommended"
          - regex: "syschecks - Path.*uses other filesystem which is not XFS or ext4"
          - regex: "unsupported configuration.*poor performance or instability"

          # Performance profiler access issues
          - regex: "Perf-based.*creation failed.*EACCESS"
          - regex: "try setting /proc/sys/kernel/perf_event_paranoid"
          - regex: "falling back to posix timer"

          # Exception handling during startup
          - regex: "Throw exception at"
          - regex: "exception - Throw exception at"

          # Development mode warnings
          - regex: "This is a setup for development purposes only"
          - regex: "clusters may run unrealistically fast and data can be corrupted"

          # Memory allocation settings
          - regex: "Setting abort_on_allocation_failure.*abort on OOM"
          - regex: "memory_abort_on_alloc_failure"

          # Crash tracking and recovery
          - regex: "crash_loop_limit"
          - regex: "Creating crash report directory"

          # Filesystem errors
          - regex: "filesystem_error.*open failed"
          - regex: "error system:2.*filesystem error"
